apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: techdemand
data:
  GATEWAY_PORT: "3000"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  COMPANY_SERVICE_URL: "http://company-service:3002"
  CONTACT_SERVICE_URL: "http://contact-service:3003"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: techdemand
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "techdemand_auth"
  DATABASE_USER: "postgres"
  JWT_EXPIRATION: "3600"
  AUTH_SERVICE_PORT: "3001"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: company-service-config
  namespace: techdemand
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "techdemand_company"
  DATABASE_USER: "postgres"
  COMPANY_SERVICE_PORT: "3002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contact-service-config
  namespace: techdemand
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "techdemand_contact"
  DATABASE_USER: "postgres"
  CONTACT_SERVICE_PORT: "3003"
