apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techdemand-ingress
  namespace: techdemand
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - techdemand.example.com
      secretName: techdemand-tls
  rules:
    - host: techdemand.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: techdemand-web
                port:
                  number: 80
